name: Laravel Deployment
on:
    push:
        branches:
            - develop
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Deploy to development
              if: github.ref == 'refs/heads/develop'
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: "${{ secrets.DEV_HOST }}"
                  username: "${{ secrets.DEV_USERNAME }}"
                  password: "${{ secrets.DEV_PASSWORD }}"
                  port: "${{ secrets.DEV_PORT }}"
                  script: |
                      cd /var/www/AP/FrontEnd
                      git fetch origin
                      git reset --hard origin/develop
                      git clean -fd
                      git pull origin develop --force
                      docker exec apf_app composer install
                      docker exec apf_app sh -c "cd /var/www/web/app/themes/sage && npm install"
                      docker exec apf_app sh -c "cd /var/www/web/app/themes/sage && npm run build"

            - name: Deploy to production
              if: github.ref == 'refs/heads/main'
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: "${{ secrets.PROD_HOST }}"
                  username: "${{ secrets.PROD_USERNAME }}"
                  password: "${{ secrets.PROD_PASSWORD }}"
                  script: |
                      cd /home/di569345/architecture-of-technology.com/www/
                      git fetch origin
                      git reset --hard origin/main
                      git clean -fd
                      git pull origin main --force
                      composer install
                      /home/di569345/architecture-of-technology.com/www/web/app/themes/sage
                      composer install

            - name: Send Telegram message
              if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
              uses: appleboy/telegram-action@v0.1.0
              with:
                  to: "${{ secrets.TELEGRAM_ID }}"
                  token: "${{ secrets.TELEGRAM_TOKEN }}"
                  message: |
                      Deployment successful https://apfront.webshum.com.ua/ on branch ${{ github.ref }}